// ── Shared styles ─────────────────────────────────────────────────────────
// Extracted from App.jsx to reduce file size.

export const s = {
  root:       {minHeight:"100vh",background:"#0e0e0e",color:"#f5f5f5"},
  header:     {borderBottom:"1px solid #1a1a1a",background:"#0e0e0e",position:"sticky",top:0,zIndex:100},
  headerInner:{maxWidth:980,margin:"0 auto",padding:"0 28px",display:"flex",alignItems:"center",justifyContent:"space-between",height:64},
  logo:       {display:"flex",alignItems:"center",gap:12},
  logoMark:   {fontSize:22,color:"#e8c468",lineHeight:1},
  logoTitle:  {fontFamily:"'Syne',sans-serif",fontWeight:700,fontSize:15,color:"#f5f5f5",letterSpacing:0.3},
  logoSub:    {fontFamily:"'Fira Code',monospace",fontSize:10,color:"#4b5563",letterSpacing:0.5},
  nav:        {display:"flex",gap:2},
  tab:        {fontFamily:"'Fira Code',monospace",fontSize:11,color:"#4b5563",background:"transparent",
               border:"none",padding:"8px 14px",borderRadius:6,cursor:"pointer",position:"relative",letterSpacing:0.3},
  tabActive:  {color:"#e8c468",background:"#1a1a1a"},
  dot:        {display:"inline-block",width:5,height:5,borderRadius:"50%",background:"#e8c468",position:"absolute",top:6,right:6},
  badge:      {display:"inline-flex",alignItems:"center",justifyContent:"center",background:"#1e1e1e",color:"#6b7280",
               borderRadius:10,fontSize:9,fontFamily:"'Fira Code',monospace",padding:"1px 5px",marginLeft:4},
  main:       {maxWidth:980,margin:"0 auto",padding:"32px 28px 60px"},
  panel:      {background:"#111",border:"1px solid #1e1e1e",borderRadius:12,padding:"28px 32px"},
  panelHead:  {marginBottom:24,paddingBottom:20,borderBottom:"1px solid #1a1a1a"},
  panelTitle: {fontFamily:"'Syne',sans-serif",fontWeight:700,fontSize:22,color:"#f5f5f5",marginBottom:6},
  panelDesc:  {fontFamily:"'Lora',serif",fontSize:13,color:"#6b7280",lineHeight:1.6,maxWidth:620},
  stepLabel:  {fontFamily:"'Fira Code',monospace",fontSize:11,color:"#e8c468",letterSpacing:0.5,marginBottom:12},
  twoCol:     {display:"grid",gridTemplateColumns:"1fr 1fr",gap:20},
  inputGroup: {display:"flex",flexDirection:"column",gap:7},
  label:      {fontFamily:"'Fira Code',monospace",fontSize:10,color:"#9ca3af",textTransform:"uppercase",letterSpacing:0.8},
  hint:       {color:"#4b5563",textTransform:"none",fontSize:10},
  textarea:   {background:"#0e0e0e",border:"1px solid #2a2a2a",borderRadius:8,color:"#d1d5db",
               fontFamily:"'Fira Code',monospace",fontSize:11.5,lineHeight:1.7,padding:"12px 14px",resize:"vertical",width:"100%"},
  input:      {background:"#0e0e0e",border:"1px solid #2a2a2a",borderRadius:8,color:"#d1d5db",
               fontFamily:"'Fira Code',monospace",fontSize:12,padding:"8px 12px",width:"100%"},
  select:     {background:"#0e0e0e",border:"1px solid #2a2a2a",borderRadius:8,color:"#d1d5db",
               fontFamily:"'Fira Code',monospace",fontSize:12,padding:"8px 12px",width:"100%",cursor:"pointer"},
  findingsBox:{background:"#0e0e0e",border:"1px solid #1e1e1e",borderRadius:8,padding:"4px 20px",maxHeight:560,overflowY:"auto"},
  empty:      {textAlign:"center",padding:"60px 20px"},
  btnGold:    {background:"#e8c468",color:"#0e0e0e",border:"none",borderRadius:8,padding:"10px 20px",
               fontFamily:"'Syne',sans-serif",fontWeight:700,fontSize:13},
  btnOutline: {background:"transparent",color:"#9ca3af",border:"1px solid #2a2a2a",borderRadius:8,
               padding:"10px 18px",fontFamily:"'Fira Code',monospace",fontSize:12},
  btn:        {background:"#1a1a1a",border:"1px solid #2a2a2a",borderRadius:6,padding:"7px 14px",
               color:"#d1d5db",fontFamily:"'Fira Code',monospace",fontSize:11,cursor:"pointer"},
  error:      {marginTop:12,padding:"10px 14px",background:"#1a0a0a",border:"1px solid #3a1a1a",
               borderRadius:6,fontFamily:"'Fira Code',monospace",fontSize:12,color:"#ef4444"},
};
